// Global Site Content
const siteContent = {
    title: "Špaňodolinské granty",
    description: "Granty sú unikátne vodné zdroje na Španej Doline a v okolí. Tieto sčasti prírodne a sčasti človekom vytvorené toky prinášali pitnú a úžitkovú vodu nielen do baní, ale aj celej obci. Kvôli chýbajúcej údržbe však vysýchajú alebo sa stávajú nepitnými. Klikni na jednotlivé body na mape alebo na jednu z trás a dozvieš sa viac.",
    contactPrompt: "Našli ste chybu? Chcete doplniť lokálny názov alebo ďalšie informácie?",
    contactLinkText: "Dajte mi vedieť.",
    contactEmail: "mailto:r.frecer@gmail.com"
};

// Thematic Routes Data
const mapRoutes = [
    {
        id: 'bansky-vodovod',
        name: 'Banský vodovod',
        color: '#2C363F', 
        file: 'assets/bansky-vodovod.gpx',
        description: 'Trasa kopírujúca zaniknutý banský vodovod.',
        slugs: ["500-bansky-vodovod", "501-bansky-vodovod", "502-bansky-vodovod", "503-bansky-vodovod", "504-bansky-vodovod"]
    },
    {
        id: 'obecne-granty',
        name: 'Obecné granty',
        color: '#007BFF',
        file: 'assets/obecne-granty.gpx',
        description: 'Prechádzka po stopách zachovalých obecných grantov.',
        slugs: ["100-pod-krasnou-horou", "112-pri-daubnerovi", "101-v-stolni", "102-pri-kostole", "108-pri-krcme", "103-denna-stolna"]
    }
];

// Map Features Data
const waterFeatures = [
    {
        id: 100,
        lat: 48.8046413708777,
        lng: 19.12642961872907,
        name: "Grant pod Krásnou horou",
        description: "Grant pod čerešňou na ceste na Krásnu horu. V roku 2021 ešte tiekol, ale v roku 2025 bol suchý.",
        type: "well",
        status: "dry",
        slug: "100-pod-krasnou-horou",
        imageCount: 1,
        yearSurveyed: 2025
    },
    {
        id: 101,
        lat: 48.80602831320122,
        lng: 19.12899953096774,
        name: "Grant v štôlni",
        description: "Výdatný aj v období sucha, tento grant je častým zdrojom vody na polievanie záhrad keď počasie neumožňuje používanie vodovodu. Grant pramení pod zemou a voda chutí vynikajúco.",
        type: "well",
        status: "drinkable",
        slug: "101-v-stolni",
        imageCount: 4,
        yearSurveyed: 2025
    },
    {
        id: 102,
        lat: 48.8079772312271,
        lng: 19.131395291223466,
        name: "Grant pri kostole",
        description: "Grant v zákrute pri kostole je vítaným osviežením pre ľudí stúpajúcich do kopca na Haldu.",
        type: "well",
        status: "drinkable",
        slug: "102-pri-kostole",
        imageCount: 1,
        yearSurveyed: 2025
    },
    {
        id: 103,
        lat: 48.807314215009555,
        lng: 19.13519788114444,
        name: "Denná štôlňa",
        description: "Z dennej štôlne vychádza prameň s nejasným zdrojom. Donedávna bol pitný, ale v roku 2024 tu presakovala odpadová voda z chalupy nad ním cez murivo samotnej štôlne. Neodporúča sa preto piť.",
        type: "well",
        status: "undrinkable",
        slug: "103-denna-stolna",
        imageCount: 3,
        yearSurveyed: 2025
    },
    {
        id: 104,
        lat: 48.80689783422882,
        lng: 19.134016878189744,
        name: "Grant nad baštou",
        description: "Tento grant má stále vodu, ale stojatá voda v koryte nad ním ho robí nepitným.",
        type: "well",
        status: "undrinkable",
        slug: "104-nad-bastou",
        imageCount: 2,
        yearSurveyed: 2025
    },
    {
        id: 105,
        lat: 48.806844349494824,
        lng: 19.13619835814387,
        name: "Zaniknutý grant",
        description: "Tento grant už neexistuje a jeho tok je suchý. Zostali po ňom len kamenné múry zasadené do svahu.",
        type: "well",
        status: "dry",
        slug: "105-zaniknuty",
        imageCount: 1,
        yearSurveyed: 2025
    },
    {
        id: 106,
        lat: 48.80652255728809,
        lng: 19.135416118177332,
        name: "Grant zo skaly",
        description: "Hoci drevené koryto tohto grantu zmizlo, voda stále vyviera zo svahu a tečie cez rúrku.",
        type: "well",
        status: "undrinkable",
        slug: "106-v-skale",
        imageCount: 2,
        yearSurveyed: 2025
    },
    {
        id: 107,
        lat: 48.808501007955734,
        lng: 19.13335321610609,
        name: "Grant pod tajchom",
        description: "Tento grant je napájaný z Tajchu, čo ho robí nepitným.",
        type: "well",
        status: "undrinkable",
        slug: "107-pod-tajchom",
        imageCount: 1,
        yearSurveyed: 2025
    },
    {
        id: 108,
        lat: 48.80786022767957,
        lng: 19.133635514215776,
        name: "Grant pri krčme",
        description: "Tento grant tiekol ešte v roku 2023, ale v roku 2025 bol úplne suchý.",
        type: "well",
        status: "dry",
        slug: "108-pri-krcme",
        imageCount: 1,
        yearSurveyed: 2025
    },
    {
        id: 109,
        lat: 48.80935918064385,
        lng: 19.132563502070436,
        name: "Grant pri Paškovi",
        description: "Tento grant je už roky suchý.",
        type: "well",
        status: "dry",
        slug: "109-pri-paskovi",
        imageCount: 2,
        yearSurveyed: 2025
    },
    {
        id: 110,
        lat: 48.80778883440417,
        lng: 19.139052804187003,
        name: "Grant pri Glósovcoch",
        description: "Tento grant je prvý v dedine z tohto toku.",
        type: "well",
        status: "undrinkable",
        slug: "110-pri-glosovcoch",
        imageCount: 1,
        yearSurveyed: 2025
    },
    {
        id: 111,
        lat: 48.803695,
        lng: 19.141332,
        name: "Dobrá voda",
        description: "Testy v roku 2016 potvrdili, že voda v grante Dobrá voda je pitná. Tento prameň sa nachádza na polceste medzi Špaňou Dolinou a Šachtičkami.",
        type: "well",
        status: "drinkable",
        slug: "111-dobra-voda",
        imageCount: 3,
        yearSurveyed: 2025
    },
    {
        id: 112,
        lat: 48.80488,
        lng: 19.12737,
        name: "Grant pri Daubnerovi",
        description: "Grant sa stal nepitným, odkedy je nad ním vybudované jazierko.",
        type: "well",
        status: "undrinkable",
        slug: "112-pri-daubnerovi",
        imageCount: 2,
        yearSurveyed: 2025
    },
    {
        id: 113,
        lat: 48.80379,
        lng: 19.12626,
        name: "Grant pri cintoríne",
        description: "Grant tečie výdatne a je pravdepodobne pitný.",
        type: "well",
        status: "drinkable",
        slug: "113-pri-cintorine",
        imageCount: 1,
        yearSurveyed: 2025
    },
    {
        id: 114,
        lat: 48.80531,
        lng: 19.13081,
        name: "Grant na Rudných baniach",
        description: "Tento grant je pravdepodobne nepitný.",
        type: "well",
        status: "undrinkable",
        slug: "114-na-rudnych-baniach",
        imageCount: 2,
        yearSurveyed: 2025
    },
    {
        id: 115,
        lat: 48.80419,
        lng: 19.13195,
        name: "Valaská 1",
        description: "Cestou na tzv. Zadky, pozemkové diely na slnečnom svahu, kde Špaňodolinčania kedysi pestovali plodiny ktoré by sa v dedine neurodili, je betónová vodovodná šachta. Kedysi tu možno stával grant. Tok z rúry už nevyteká, ale vylieva sa vyššie vo svahu naokolo.",
        type: "well",
        status: "undrinkable",
        slug: "115-valaska",
        imageCount: 1,
        yearSurveyed: 2025
    },
    {
        id: 500,
        lat: 48.81218888112165,
        lng: 19.128767529422998,
        name: "Banský vodovod 1",
        description: "Veľké bridlicové kamene, ktorými bol tok banského vodovodu prikrytý.",
        type: "stream",
        status: "dry",
        slug: "500-bansky-vodovod",
        imageCount: 1,
        yearSurveyed: 2025
    },
    {
        id: 501,
        lat: 48.81187963120183,
        lng: 19.128830295239183,
        name: "Banský vodovod 2",
        description: "Priehlbiny na okraji cesty, v ktorých je stále viditeľné koryto banského vodovodu vystlané kameňmi.",
        type: "stream",
        status: "dry",
        slug: "501-bansky-vodovod",
        imageCount: 3,
        yearSurveyed: 2025
    },
    {
        id: 502,
        lat: 48.81157118812032,
        lng: 19.129046440784304,
        name: "Banský vodovod 3",
        description: "Priehlbiny na okraji cesty, v ktorých je stále viditeľné koryto banského vodovodu vystlané kameňmi. Sú tu dobre zachované tri bridlicové prikrývacie kamene za sebou.",
        type: "stream",
        status: "dry",
        slug: "502-bansky-vodovod",
        imageCount: 3,
        yearSurveyed: 2025
    },
    {
        id: 503,
        lat: 48.812821006846646,
        lng: 19.133277664587368,
        name: "Banský vodovod 4",
        description: "Koryto banského vodovodu je pod zemou miestami zachovalé, že ho využívajú zvieratá ako nory.",
        type: "stream",
        status: "dry",
        slug: "503-bansky-vodovod",
        imageCount: 1,
        yearSurveyed: 2025
    },
    {
        id: 504,
        lat: 48.813412527196476,
        lng: 19.134307725177674,
        name: "Banský vodovod 5",
        description: "Miestami je koryto tak zasypané, že vykukje len málo.",
        type: "stream",
        status: "dry",
        slug: "504-bansky-vodovod",
        imageCount: 2,
        yearSurveyed: 2025
    },
    {
        id: 505,
        lat: 48.80766,
        lng: 19.13779,
        name: "Horný koniec",
        description: "Upravený tok pomedzi záhrady.",
        type: "stream",
        status: "undrinkable",
        slug: "505-horny-koniec",
        imageCount: 1,
        yearSurveyed: 2025
    },
    {
        id: 506,
        lat: 48.80739,
        lng: 19.13889,
        name: "Fajtlová 1",
        description: "Posledný úsek toku Fajtlová pred napojením na Dobrú vodu. Upravené koryto murovanými kameňmi pomedzi záhrady.",
        type: "stream",
        status: "undrinkable",
        slug: "506-fajtlova",
        imageCount: 1,
        yearSurveyed: 2025
    },
    {
        id: 507,
        lat: 48.80721,
        lng: 19.13899,
        name: "Dobrá voda 1",
        description: "Posledný úsek toku Dobrá voda pred napojením na Fajtlovú je vedený novými podzemnými rúrami. Kvôli domom nad ním je pravdepodobne nepitný.",
        type: "stream",
        status: "undrinkable",
        slug: "507-dobra-voda",
        imageCount: 3,
        yearSurveyed: 2025
    },
    {
        id: 508,
        lat: 48.807802,
        lng: 19.131493,
        name: "Pri kostole",
        description: "Nepatrné zvyšky suchého toku v zákrute pri kostole. Podľa Vlada Bíreša tu kedysi stával grant.",
        type: "stream",
        status: "dry",
        slug: "508-pri-kostole",
        imageCount: 1,
        yearSurveyed: 2025
    },
    {
        id: 509,
        lat: 48.80759,
        lng: 19.130303,
        name: "V rýničke",
        description: "Podľa mapy tento tok môže prameniť spod haldy šachty Ludovika - vynáša teda odpadovú vodu použitú v baniach, podobne ako prameň pri Tajchu pod haldou šachty Maximilián.",
        type: "stream",
        status: "undrinkable",
        slug: "509-v-rynicke",
        imageCount: 1,
        yearSurveyed: 2025
    },
    {
        id: 510,
        lat: 48.805083,
        lng: 19.12724,
        name: "Nad Daubnerom",
        description: "Nejasný tok zo svahu.",
        type: "stream",
        status: "undrinkable",
        slug: "510-nad-daubnerom",
        imageCount: 1,
        yearSurveyed: 2025
    },
    {
        id: 511,
        lat: 48.8087,
        lng: 19.13321,
        name: "Tajch",
        description: "Prameň spod haldy prepúšťal užitú vodu zo šácht Maximilián a Ludovika, aby ďalej slúžila na pohon banskych strojov na Pľaci.",
        type: "stream",
        status: "undrinkable",
        slug: "511-tajch",
        imageCount: 3,
        yearSurveyed: 2025
    },
    {
        id: 512,
        lat: 48.80824,
        lng: 19.13344,
        name: "Pod tajchom",
        description: "Upravený tok vody s hlbokým murovaným korytom.",
        type: "stream",
        status: "undrinkable",
        slug: "512-pod-tajchom",
        imageCount: 3,
        yearSurveyed: 2025
    },
    {
        id: 513,
        lat: 48.80663,
        lng: 19.13976,
        name: "Dobrá voda 2",
        description: "Pri posledných domoch v dedine tečie Dobrá voda divokým korytom. Nie je vylúčené, že do toku tečie odpadová voda.",
        type: "stream",
        status: "undrinkable",
        slug: "513-dobra-voda",
        imageCount: 3,
        yearSurveyed: 2025
    },
    {
        id: 514,
        lat: 48.80588,
        lng: 19.14023,
        name: "Dobrá voda 3",
        description: "Za poslednými domami do Dobrej vody priteká ďalší lesný potok z juhovýchodnej strany lesa. Koryto je rozvetvené a vytvára brázdy.",
        type: "stream",
        status: "undrinkable",
        slug: "514-dobra-voda",
        imageCount: 4,
        yearSurveyed: 2025
    },
    {
        id: 515,
        lat: 48.80526,
        lng: 19.13911,
        name: "Mláky v lese",
        description: "Na tomto mieste v lese sa držia mláky, v roku 2024 tu bolo aj malé jazierko. Mohol by to byť zaniknutý tajch.",
        type: "stream",
        status: "undrinkable",
        slug: "515-mlaky",
        imageCount: 2,
        yearSurveyed: 2025
    },
    {
        id: 516,
        lat: 48.80392,
        lng: 19.14196,
        name: "Pri Dobrej vode",
        description: "Na križovatke toku Dobrej vody a lesnej vrstevnice pokračuje tok popri ceste v brázde.",
        type: "stream",
        status: "undrinkable",
        slug: "516-pri-dobrej-vode",
        imageCount: 1,
        yearSurveyed: 2025
    },
    {
        id: 517,
        lat: 48.805352,
        lng: 19.143722,
        name: "V zákrute",
        description: "V zákrute na vrstevnici tečie zhora z lesa voda upravenou rúrou popod cestu.",
        type: "stream",
        status: "undrinkable",
        slug: "517-v-zakrute",
        imageCount: 1,
        yearSurveyed: 2025
    },
    {
        id: 518,
        lat: 48.8112,
        lng: 19.1436,
        name: "Za zákrutou",
        description: "Za zákrutou na vrstevnici sa drží stojatá voda. Tok popri vrstevnici tu končí a vylieva sa dole smerom do dediny.",
        type: "stream",
        status: "undrinkable",
        slug: "518-za-zakrutou",
        imageCount: 1,
        yearSurveyed: 2025
    },
    {
        id: 519,
        lat: 48.8102,
        lng: 19.13991,
        name: "Štôlňa Mann",
        description: "V štôlni Mann stojí voda a prilieva sa do toku Fajtlovej. Okolie je plné mravenísk.",
        type: "stream",
        status: "undrinkable",
        slug: "519-stolna-mann",
        imageCount: 3,
        yearSurveyed: 2025
    },
    {
        id: 520,
        lat: 48.80258,
        lng: 19.1185,
        name: "Cestou na Trojicu",
        description: "Cestou ku lesnej kaplnke Sv. Trojice tečie kopcom prameň, ktorý bol kedysi zakrytý strieškou. Dnes je takmer suchý, iba okolie je podmočené.",
        type: "stream",
        status: "dry",
        slug: "520-na-trojicu",
        imageCount: 2,
        yearSurveyed: 2025
    },
    {
        id: 521,
        lat: 48.81834,
        lng: 19.12634,
        name: "Piesky",
        description: "Zo štôlne pri kaplnke na Pieskoch vyteká voda, ktorá vytvára koryto potoka smerom na Staré Hory. Voda vyviera zo skalnej steny vnútri v štôlni, a je preto pravdepodobne pitná.",
        type: "stream",
        status: "drinkable",
        slug: "521-piesky",
        imageCount: 2,
        yearSurveyed: 2025
    },
    {
        id: 522,
        lat: 48.8038,
        lng: 19.12518,
        name: "Prekop Špania Dolina - Piesky",
        description: "Pri hĺbení banského prekopu zo Španej Doliny na Piesky v 60. rokoch objavili zdroj pitnej vody, ktorý je vedený krytým korytom vedľa koľajníc. Touto vodou je zásobovaná časť dediny Krásna Hora.",
        type: "stream",
        status: "drinkable",
        slug: "522-prekop",
        imageCount: 1,
        yearSurveyed: 2025
    },
    {
        id: 523,
        lat: 48.80384,
        lng: 19.13206,
        name: "Valaská 2",
        description: "Cestou na tzv. Zadky, pozemkové diely na slnečnom svahu, kde Špaňodolinčania kedysi pestovali plodiny ktoré by sa v dedine neurodili, je podmáčaná pôda z neregulovaného vodného toku.",
        type: "stream",
        status: "undrinkable",
        slug: "523-valaska",
        imageCount: 2,
        yearSurveyed: 2025
    },
    {
        id: 524,
        lat: 48.80421,
        lng: 19.1325,
        name: "Valaská 3",
        description: "Cestou na tzv. Zadky, pozemkové diely na slnečnom svahu, kde Špaňodolinčania kedysi pestovali plodiny ktoré by sa v dedine neurodili, je podmáčaná pôda z neregulovaného vodného toku.",
        type: "stream",
        status: "undrinkable",
        slug: "524-valaska",
        imageCount: 1,
        yearSurveyed: 2025
    }
];